[package]
name = "eggo"
version = "0.1.0"
authors = ["Remy Wang <remywang@uw.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.4.0"
